services:
  db:
    image: postgres:15
    container_name: asistanto-db
    environment:
      POSTGRES_DB: asistanto_db
      POSTGRES_USER: asistanto_user
      POSTGRES_PASSWORD: secret
      TZ: "Europe/Bratislava"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asistanto-network
    restart: unless-stopped

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php-fpm
    container_name: asistanto-php-fpm
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      TZ: "Europe/Bratislava"
    depends_on:
      - db
    networks:
      - asistanto-network
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    container_name: asistanto-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    networks:
      - asistanto-network
    restart: unless-stopped

  frontend-customer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-customer
    container_name: asistanto-customer
    volumes:
      - ./frontend-customer:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3001
    depends_on:
      - php-fpm
    networks:
      - asistanto-network
    restart: unless-stopped

  frontend-employee:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-employee
    container_name: asistanto-employee
    volumes:
      - ./frontend-employee:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3002
    depends_on:
      - php-fpm
    networks:
      - asistanto-network
    restart: unless-stopped

  frontend-admin:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-admin
    container_name: asistanto-admin
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3003
    depends_on:
      - php-fpm
    networks:
      - asistanto-network
    restart: unless-stopped

networks:
  asistanto-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local