services:
  db:
    image: postgres:15
    container_name: asistanto-db
    environment:
      POSTGRES_DB: asistanto_db
      POSTGRES_USER: asistanto_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - asistanto-network
    restart: unless-stopped

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php-fpm
    container_name: asistanto-php-fpm
    volumes:
      - ./backend:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    networks:
      - asistanto-network
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    container_name: asistanto-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - asistanto-network
    restart: unless-stopped

  frontend-customer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-customer
    container_name: asistanto-customer
    volumes:
      - ./frontend-customer:/app
    ports:
      - "3001:3001"  # zmeň na rovnaký port
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3001
    depends_on:
      - php-fpm
    networks:
      - asistanto-network
    restart: unless-stopped

# Podobne pre ostatné frontendy

  frontend-employee:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-employee
    container_name: asistanto-employee
    volumes:
      - ./frontend-employee:/app
    ports:
      - "3002:3002"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3002
    depends_on:
      - php-fpm
    networks:
      - asistanto-network
    restart: unless-stopped

  frontend-admin:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-admin
    container_name: asistanto-admin
    volumes:
      - ./frontend-admin:/app
    ports:
      - "3003:3003"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3003
    depends_on:
      - php-fpm
    networks:
      - asistanto-network
    restart: unless-stopped

networks:
  asistanto-network:
    driver: bridge

volumes:
  db_data:
