services:
  db:
    image: postgres:15
    container_name: asistanto-db
    environment:
      POSTGRES_DB: asistanto_db
      POSTGRES_USER: asistanto_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - asistanto-network

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php-fpm
    container_name: asistanto-php-fpm
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - asistanto-network

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    container_name: asistanto-nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - asistanto-network

  frontend-tailwind:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-tailwind
    container_name: asistanto-tailwind
    volumes:
      - ./frontend-tailwind:/app
    ports:
      - "3001:3000"
    depends_on:
      - php-fpm
    networks:
      - asistanto-network

  frontend-bootstrap:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-bootstrap
    container_name: asistanto-bootstrap
    volumes:
      - ./frontend-bootstrap:/app
    ports:
      - "3002:3000"
    depends_on:
      - php-fpm
    networks:
      - asistanto-network

  frontend-admin:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-admin
    container_name: asistanto-admin
    volumes:
      - ./frontend-admin:/app
    ports:
      - "3003:3000"
    depends_on:
      - php-fpm
    networks:
      - asistanto-network

networks:
  asistanto-network:
    driver: bridge

volumes:
  db_data:
