FROM php:8.1-fpm

# Nainštalujeme rozšírenia pre PostgreSQL
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo_pgsql

# Nainštalujeme Composer
COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

# Nastav vlastníka na www-data (alebo php)
# RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Nastav oprávnenia
# RUN chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

WORKDIR /var/www/html
EXPOSE 9000
CMD ["php-fpm"]
