FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY ./frontend-employee/package*.json ./

# Inštalujeme závislosti globálne
RUN npm install -g vite

# Inštalujeme lokálne závislosti
RUN npm install --platform=linux/amd64

COPY ./frontend-employee/ ./

ENV VITE_HOST=0.0.0.0
ENV VITE_PORT=3002

EXPOSE 3002

# Upravíme príkaz na spustenie
CMD ["npm", "run", "dev"]