FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY ./frontend-admin/package*.json ./

RUN npm install --platform=linux/amd64

COPY ./frontend-admin/ ./

ENV VITE_HOST=0.0.0.0
ENV VITE_PORT=3003

EXPOSE 3003

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3003"]