FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY ./frontend-bootstrap/package*.json ./

RUN npm install --platform=linux/amd64

COPY ./frontend-bootstrap/ ./

ENV VITE_HOST=0.0.0.0
ENV VITE_PORT=3002

EXPOSE 3002

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3002"]